services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    container_name: devsim-keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USERNAME:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      - KC_DB=h2
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak/realm-config:/opt/keycloak/data/import:ro
    command: 
      - start-dev
      - --import-realm
    networks:
      - devsim-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;grep -q '200 OK' <&3"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  backend:
    build: ./backend
    container_name: devsim-backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./backend/uploads:/app/uploads
      # Mount secrets directory for secure key storage
      - ./data/secrets:/app/data/secrets:ro
      - ./data/keys:/app/data/keys:ro
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_APP=run.py
      - DATABASE_URL=${DATABASE_URL:-sqlite:////app/data/scheduler_jobs.db}
      # Security Configuration
      - SECRET_KEY=${SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - ENCRYPTION_KEY_VERSION=${ENCRYPTION_KEY_VERSION:-1}
      # Authentication Configuration
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AUTHENTICATION_ENABLED=${AUTHENTICATION_ENABLED:-false}
      # Keycloak Configuration
      - KEYCLOAK_ENABLED=${KEYCLOAK_ENABLED:-false}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL:-http://keycloak:8080}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM:-devsim}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:-devsim-app}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      # Secret Management Configuration
      - USE_DOCKER_SECRETS=${USE_DOCKER_SECRETS:-false}
      - SECRET_ENV_PREFIX=${SECRET_ENV_PREFIX:-DEVSIM_}
      - ENCRYPTION_KEY_STORAGE_PATH=/app/data/keys
      - SECRETS_STORAGE_DIR=/app/data/secrets
      # Upload Configuration
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH:-10485760}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER:-/app/uploads}
      # Development Settings
      - ALLOW_SENSITIVE_CONNECTIONS=${ALLOW_SENSITIVE_CONNECTIONS:-false}
    env_file:
      - .env
    secrets:
      - encryption_key
      - jwt_secret
      - db_password
    networks:
      - devsim-network
    restart: unless-stopped
    depends_on:
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: devsim-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - devsim-network
    restart: unless-stopped

networks:
  devsim-network:
    driver: bridge

volumes:
  devsim-data:
    driver: local
  devsim-uploads:
    driver: local
  keycloak-data:
    driver: local

# Docker Secrets for production deployment
secrets:
  encryption_key:
    file: ./secrets/encryption_key.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  db_password:
    file: ./secrets/db_password.txt
